version: '3.4'

services:
  rabbitmq.consumer:
    image: rabbitmqconsumer:dev
    container_name: RabbitMq.Consumer
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "RabbitMq.Consumer"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_rabbitmq.consumer$
    volumes:
      - D:\Programming\ATL\UserRegistirationApp\RabbitMq.Consumer:/app
      - D:\Programming\ATL\UserRegistirationApp:/src
      - C:\Users\User\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_rabbitmq.consumer$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_rabbitmq.consumer$ \"/app/bin/Debug/net5.0/RabbitMq.Consumer.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  userregistirationapp.webui:
    image: userregistirationappwebui:dev
    container_name: UserRegistirationApp.WebUi
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "UserRegistirationApp.WebUi"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_userregistirationapp.webui$
    volumes:
      - D:\Programming\ATL\UserRegistirationApp\UserRegistirationApp.WebUi:/app
      - D:\Programming\ATL\UserRegistirationApp:/src
      - C:\Users\User\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_userregistirationapp.webui$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_userregistirationapp.webui$ \"/app/bin/Debug/net5.0/UserRegistirationApp.WebUi.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
